print(0o10)
print(0b10)
print(0x10)
print(type(10))
print(4.2)
print(type(4.2))
print(2+3j)
print(type(2+3j))
print("I am luffy..i am gonna be king of pirates")
print(type("I am luffy..i am gonna be king of pirates"))
print(type(True))
print(type(False))

print("thejg jahdufh (') vhuqwdiqi")
print('huihewhfiu (")iuhuuie')